Routing
DeeaMG/payments-portal pull request #1
Opened 2023-09-18 17:39 UTC by DeeaMG

There is a problem with edit mode of MUI data grid. The state doesn't change on first click, just on the second one.

2023-09-20 07:46 UTC, enfrbhd requested changes

2023-09-20 07:46 UTC, enfrbhd commented on src/components/Payments/Payments.tsx
> +        console.log(data);
please don't commit logs to PRs

2023-09-20 07:46 UTC, enfrbhd commented on src/components/Payments/Payments.api.ts
> +    throw new Error("Error fetching payments: " + error.message);
instead of throwing the error. you can collect it as a notification from the request. and show the notification on the frontend with a toast component

2023-09-20 07:46 UTC, enfrbhd commented on src/App.tsx
> +        <Route path='/payments' element={<Payments />} />
please use React lazy in combination with Suspense in order to achieve lazy loading on routes

https://react.dev/reference/react/lazy
https://react.dev/reference/react/Suspense

2023-09-20 07:46 UTC, enfrbhd commented on src/components/Payments/Payments.tsx
> +  const handleCellEdit = async (params: any) => {
params should not be of type any, you should define an interface for it

2023-09-20 07:46 UTC, enfrbhd commented on src/utils/ObjectEquality.ts
> +export function deepEqual(x: any, y: any): boolean {
you can use https://lodash.com/docs/4.17.15#isEqual instead of this method, it covers more cases, and you can include only that method in the build so you don't load the entire library.

2023-09-20 07:46 UTC, enfrbhd commented on src/components/Payments/Payments.api.ts
> +  console.log("This is the payment object: ", payment);
please don't use logs in PRs

2023-09-20 17:26 UTC, DeeaMG commented on src/components/Payments/Payments.tsx
> +        console.log(data);
Done it in [f6c80cc](https://github.com/DeeaMG/payments-portal/pull/1/commits/f6c80cc49b99de24921fbd404c56f72b8d91a0dd)

2023-09-20 17:26 UTC, DeeaMG commented on src/components/Payments/Payments.api.ts
> +  console.log("This is the payment object: ", payment);
Resolved it in [f6c80cc](https://github.com/DeeaMG/payments-portal/pull/1/commits/f6c80cc49b99de24921fbd404c56f72b8d91a0dd)

2023-09-20 17:27 UTC, DeeaMG commented on src/App.tsx
> +        <Route path='/payments' element={<Payments />} />
Resolved it in [c2c2332](https://github.com/DeeaMG/payments-portal/pull/1/commits/c2c23323650ad7624874772441a1604e6cdef9b0)

2023-09-20 19:02 UTC, DeeaMG commented on src/components/Payments/Payments.tsx
> +  const handleCellEdit = async (params: any) => {
I can't find the proper type, or how should the interface look like.

2023-09-20 19:14 UTC, DeeaMG commented on src/utils/ObjectEquality.ts
> +export function deepEqual(x: any, y: any): boolean {
Resolved in [8e279e4](https://github.com/DeeaMG/payments-portal/pull/1/commits/8e279e4e483378d31292213e6bd9be47ebaea12a)

2023-09-20 19:38 UTC, DeeaMG commented on src/components/Payments/Payments.tsx
> +  const handleCellEdit = async (params: any) => {
Solved in [46891ac](https://github.com/DeeaMG/payments-portal/pull/1/commits/46891acdf7ed469b5188846f6b7ef171b1685f38)

2023-09-22 05:09 UTC, enfrbhd commented on src/components/Payments/Payments.tsx
> +          (product: any) => `${product.name}: $${product.totalPrice}`
product should not be of type any

2023-09-22 05:09 UTC, enfrbhd commented on src/components/Payments/Payments.tsx
> +        (paymentToUpdate as any)[field] = value;
paymentToUpdate should not be of type any

2023-09-22 05:09 UTC, enfrbhd commented on src/components/Payments/Payments.tsx
> +        console.error(error);
notifications should be set on catch

2023-09-22 05:09 UTC, enfrbhd commented on src/components/Payments/Payments.api.ts
> +  } catch (error: any) {
error should not be of type any

2023-09-25 07:20 UTC, DeeaMG commented on src/components/Payments/Payments.tsx
> +          (product: any) => `${product.name}: $${product.totalPrice}`
Resolved in [4528c68](https://github.com/DeeaMG/payments-portal/pull/1/commits/4528c6821aab6094f2fd8e8d72b28e72868e40e1)

2023-09-25 07:25 UTC, DeeaMG commented on src/components/Payments/Payments.tsx
> +        (paymentToUpdate as any)[field] = value;
![image](https://github.com/DeeaMG/payments-portal/assets/55800409/d6c07286-fcb4-4a42-ac4d-5d859919ae42)
![image](https://github.com/DeeaMG/payments-portal/assets/55800409/b2bb9189-cd32-47b4-aae7-9824cd9b484d)

2023-09-25 07:26 UTC, DeeaMG commented on src/components/Payments/Payments.tsx
> +        (paymentToUpdate as any)[field] = value;
The problem is that is not working without type any.

2023-09-25 07:42 UTC, DeeaMG commented on src/components/Payments/Payments.api.ts
> +  } catch (error: any) {
Resolved in [30d5663](https://github.com/DeeaMG/payments-portal/pull/1/commits/30d5663adb8359a7c05a93c98b47c6bfc32f7794)

2023-09-25 08:50 UTC, DeeaMG commented on src/components/Payments/Payments.tsx
> +        console.error(error);
Partially solved in [902c629](https://github.com/DeeaMG/payments-portal/pull/1/commits/902c62954fb95d006759002738604e19821dd71a)

2023-09-25 08:50 UTC, DeeaMG commented on src/components/Payments/Payments.api.ts
> +    throw new Error("Error fetching payments: " + error.message);
Partially solved in [902c629](https://github.com/DeeaMG/payments-portal/pull/1/commits/902c62954fb95d006759002738604e19821dd71a)

2023-09-25 08:51 UTC, DeeaMG commented on src/components/Payments/Payments.api.ts
> +    throw new Error("Error fetching payments: " + error.message);
I need to delete the message after successfully fetching the data.

2023-09-26 08:46 UTC, enfrbhd approved these changes

2023-09-26 08:46 UTC, enfrbhd commented on src/components/Payments/Payments.tsx
> +        (paymentToUpdate as any)[field] = value;
you can define it as Record<string, string> instead of any when you type cast it

2023-09-26 08:47 UTC, merged